-- ============================================================================
-- 1. ENUMS & TYPES
-- ============================================================================
CREATE TYPE invoice_type AS ENUM ('sale', 'purchase');
CREATE TYPE invoice_status AS ENUM ('paid', 'partial', 'unpaid');
CREATE TYPE payment_status_type AS ENUM ('draft', 'confirmed', 'cancelled');
CREATE TYPE payment_method_type AS ENUM ('cash', 'check', 'bank_transfer', 'other');
CREATE TYPE payment_type_enum AS ENUM ('collection', 'disbursement');
CREATE TYPE order_status_type AS ENUM ('pending', 'inProgress', 'completed', 'cancelled');
CREATE TYPE item_type_enum AS ENUM ('raw_materials', 'packaging_materials', 'semi_finished_products', 'finished_products');

-- ============================================================================
-- 2. INVENTORY (Master Data)
-- ============================================================================

-- Raw Materials (المواد الخام)
CREATE TABLE raw_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  unit TEXT NOT NULL,
  quantity NUMERIC NOT NULL DEFAULT 0,
  min_stock NUMERIC NOT NULL DEFAULT 0,
  unit_cost NUMERIC NOT NULL DEFAULT 0,
  importance INTEGER DEFAULT 0,
  sales_price NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Packaging Materials (مواد التعبئة والتغليف)
CREATE TABLE packaging_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  unit TEXT NOT NULL,
  quantity NUMERIC NOT NULL DEFAULT 0,
  min_stock NUMERIC NOT NULL DEFAULT 0,
  unit_cost NUMERIC NOT NULL DEFAULT 0,
  sales_price NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Semi Finished Products (منتجات نصف مصنعة)
CREATE TABLE semi_finished_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  unit TEXT NOT NULL,
  quantity NUMERIC NOT NULL DEFAULT 0,
  min_stock NUMERIC NOT NULL DEFAULT 0,
  unit_cost NUMERIC NOT NULL DEFAULT 0,
  sales_price NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Semi Finished Ingredients (مكونات المنتج نصف المصنع - الوصفة)
CREATE TABLE semi_finished_ingredients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semi_finished_id BIGINT REFERENCES semi_finished_products(id) ON DELETE CASCADE,
  raw_material_id BIGINT REFERENCES raw_materials(id) ON DELETE RESTRICT,
  percentage NUMERIC NOT NULL, -- Percentage of the total quantity or quantity per unit
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Finished Products (منتجات تامة الصنع)
CREATE TABLE finished_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  unit TEXT NOT NULL,
  quantity NUMERIC NOT NULL DEFAULT 0,
  min_stock NUMERIC NOT NULL DEFAULT 0,
  unit_cost NUMERIC NOT NULL DEFAULT 0,
  sales_price NUMERIC DEFAULT 0,
  semi_finished_id BIGINT REFERENCES semi_finished_products(id) ON DELETE RESTRICT,
  semi_finished_quantity NUMERIC NOT NULL DEFAULT 1, -- Quantity of semi-finished needed for 1 unit of finished
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Finished Product Packaging (مواد تعبئة المنتج التام)
CREATE TABLE finished_product_packaging (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  finished_product_id BIGINT REFERENCES finished_products(id) ON DELETE CASCADE,
  packaging_material_id BIGINT REFERENCES packaging_materials(id) ON DELETE RESTRICT,
  quantity NUMERIC NOT NULL, -- Quantity needed per 1 unit of finished product
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Inventory Movements Log (سجل حركات المخزون)
CREATE TABLE inventory_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id BIGINT NOT NULL,
  item_type item_type_enum NOT NULL,
  movement_type TEXT NOT NULL, -- 'in', 'out', 'adjustment'
  quantity NUMERIC NOT NULL,
  previous_balance NUMERIC,
  new_balance NUMERIC,
  reason TEXT,
  reference_id TEXT, -- Order ID, Invoice ID, etc.
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- 3. PARTIES (Commercial)
-- ============================================================================
CREATE TABLE parties (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL, -- 'customer', 'supplier'
  phone TEXT,
  address TEXT,
  email TEXT,
  balance NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- 4. PRODUCTION (Enhanced for Multi-Item)
-- ============================================================================

-- Production Orders Header
CREATE TABLE production_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  status order_status_type NOT NULL DEFAULT 'pending',
  notes TEXT,
  total_cost NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Production Order Items (The products being produced)
CREATE TABLE production_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id BIGINT REFERENCES production_orders(id) ON DELETE CASCADE,
  semi_finished_id BIGINT REFERENCES semi_finished_products(id) ON DELETE RESTRICT,
  quantity NUMERIC NOT NULL,
  unit_cost NUMERIC DEFAULT 0, -- Snapshot of cost at time of production
  total_cost NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Production Order Ingredients (Raw materials consumed - Calculated or Manual Override)
-- This allows tracking exact consumption per order if needed, aggregated for all items in the order
CREATE TABLE production_order_consumed_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id BIGINT REFERENCES production_orders(id) ON DELETE CASCADE,
  raw_material_id BIGINT REFERENCES raw_materials(id) ON DELETE RESTRICT,
  quantity NUMERIC NOT NULL,
  unit_cost NUMERIC DEFAULT 0,
  total_cost NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================================
-- 5. PACKAGING (Enhanced for Multi-Item)
-- ============================================================================

-- Packaging Orders Header
CREATE TABLE packaging_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  status order_status_type NOT NULL DEFAULT 'pending',
  notes TEXT,
  total_cost NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Packaging Order Items (The finished products being packed)
CREATE TABLE packaging_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  packaging_order_id BIGINT REFERENCES packaging_orders(id) ON DELETE CASCADE,
  finished_product_id BIGINT REFERENCES finished_products(id) ON DELETE RESTRICT,
  quantity NUMERIC NOT NULL,
  unit_cost NUMERIC DEFAULT 0,
  total_cost NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Packaging Order Materials (Items Consumed: Semi-Finished + Packaging Materials)
CREATE TABLE packaging_order_consumed_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  packaging_order_id BIGINT REFERENCES packaging_orders(id) ON DELETE CASCADE,
  item_id BIGINT NOT NULL, -- Can be semi_finished_id or packaging_material_id
  item_type TEXT NOT NULL, -- 'semi_finished' or 'packaging_material'
  quantity NUMERIC NOT NULL,
  unit_cost NUMERIC DEFAULT 0,
  total_cost NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- 6. COMMERCIAL (Invoices & Payments)
-- ============================================================================

-- Invoices
CREATE TABLE invoices (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  code TEXT, -- Invoice Number
  invoice_type invoice_type NOT NULL,
  party_id UUID REFERENCES parties(id) ON DELETE SET NULL,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  total_amount NUMERIC NOT NULL DEFAULT 0,
  paid_amount NUMERIC DEFAULT 0,
  remaining_amount NUMERIC GENERATED ALWAYS AS (total_amount - paid_amount) STORED,
  status invoice_status DEFAULT 'unpaid',
  payment_status payment_status_type DEFAULT 'draft',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Invoice Items
CREATE TABLE invoice_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  invoice_id UUID REFERENCES invoices(id) ON DELETE CASCADE,
  item_id BIGINT NOT NULL,
  item_type item_type_enum NOT NULL,
  quantity NUMERIC NOT NULL,
  unit_price NUMERIC NOT NULL,
  total NUMERIC GENERATED ALWAYS AS (quantity * unit_price) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Payments
CREATE TABLE payments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  code TEXT,
  party_id UUID REFERENCES parties(id) ON DELETE SET NULL,
  amount NUMERIC NOT NULL,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  payment_type payment_type_enum NOT NULL,
  method payment_method_type DEFAULT 'cash',
  reference_number TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- 7. FINANCIAL (Ledger)
-- ============================================================================

CREATE TABLE ledger_entries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  party_id UUID REFERENCES parties(id),
  transaction_date DATE NOT NULL,
  description TEXT,
  debit NUMERIC DEFAULT 0,
  credit NUMERIC DEFAULT 0,
  reference_type TEXT, -- 'invoice', 'payment', 'return'
  reference_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE OR REPLACE VIEW party_balances AS
SELECT 
  party_id,
  SUM(debit - credit) as balance
FROM ledger_entries
GROUP BY party_id;
