import { z } from 'zod';
const alias=z.enum(['a0','a1','a2','a3','a4','a5']);
const output=z.string().regex(/^[a-z][a-z0-9_]{0,31}$/);
const column=z.enum(["id","code","name","unit","quantity","min_stock","unit_cost","sales_price","created_at","updated_at","importance","recipe_batch_size","semi_finished_id","semi_finished_quantity","bundle_price","is_active","type","balance","credit_limit","currency","is_system","treasury_id","party_id","amount","transaction_type","category","reference_type","reference_id","transaction_date","invoice_id","invoice_type","invoice_number","customer_id","total_amount","paid_amount","tax_amount","discount_amount","shipping_cost","status","supplier_id","item_type","raw_material_id","packaging_material_id","finished_product_id","semi_finished_product_id","unit_price","total_price","unit_cost_at_sale","bundle_id","return_number","original_invoice_id","return_date","return_id","unit_cost_at_return","date","total_cost","production_order_id","packaging_order_id","assembly_order_id","percentage","item_id","session_id","product_name","system_quantity","counted_quantity","difference","cost_impact","movement_type","previous_balance","new_balance"]);
const field=z.object({alias,column}).strict();
const columnExpr=z.object({kind:z.literal('column'),field}).strict();
const product=z.object({kind:z.literal('product'),left:field,right:field}).strict();
const scalarExpr=z.union([columnExpr,product]);
const aggregate=z.object({kind:z.literal('aggregate'),fn:z.enum(['count','sum','avg','min','max']),expr:scalarExpr.optional()}).strict()
 .superRefine((v,c)=>{if(v.fn!=='count'&&!v.expr)c.addIssue({code:'custom',message:'expr is required except count(*)'});});
const scalar=z.union([z.string().max(500),z.number().finite().min(-1e12).max(1e12),z.boolean()]);
export const analyticalQuery=z.object({
 from:z.object({table:z.enum(["raw_materials","packaging_materials","semi_finished_products","finished_products","product_bundles","parties","treasuries","financial_categories","financial_transactions","sales_invoices","purchase_invoices","sales_invoice_items","purchase_invoice_items","sales_returns","purchase_returns","sales_return_items","purchase_return_items","production_orders","packaging_orders","bundle_assembly_orders","production_order_items","packaging_order_items","bundle_assembly_order_items","semi_finished_ingredients","finished_product_packaging","bundle_items","production_order_consumed_materials","packaging_order_consumed_materials","inventory_count_sessions","inventory_count_items","inventory_movements"]),alias}).strict(),
 joins:z.array(z.object({relationship:z.enum(["sales_invoices.customer_id","sales_returns.customer_id","purchase_invoices.supplier_id","purchase_returns.supplier_id","sales_invoices.treasury_id","purchase_invoices.treasury_id","financial_transactions.treasury_id","financial_transactions.party_id","sales_invoice_items.invoice_id","sales_return_items.return_id","sales_returns.original_invoice_id","sales_invoice_items.raw_material_id","sales_invoice_items.packaging_material_id","sales_invoice_items.finished_product_id","sales_invoice_items.semi_finished_product_id","sales_return_items.raw_material_id","sales_return_items.packaging_material_id","sales_return_items.finished_product_id","sales_return_items.semi_finished_product_id","purchase_invoice_items.invoice_id","purchase_return_items.return_id","purchase_returns.original_invoice_id","purchase_invoice_items.raw_material_id","purchase_invoice_items.packaging_material_id","purchase_invoice_items.finished_product_id","purchase_invoice_items.semi_finished_product_id","purchase_return_items.raw_material_id","purchase_return_items.packaging_material_id","purchase_return_items.finished_product_id","purchase_return_items.semi_finished_product_id","sales_invoice_items.bundle_id","sales_return_items.bundle_id","finished_products.semi_finished_id","semi_finished_ingredients.semi_finished_id","semi_finished_ingredients.raw_material_id","finished_product_packaging.finished_product_id","finished_product_packaging.packaging_material_id","production_order_items.production_order_id","production_order_items.semi_finished_id","packaging_order_items.packaging_order_id","packaging_order_items.finished_product_id","bundle_assembly_order_items.assembly_order_id","bundle_assembly_order_items.bundle_id","bundle_items.bundle_id","bundle_items.finished_product_id","bundle_items.semi_finished_product_id","bundle_items.raw_material_id","bundle_items.packaging_material_id","production_order_consumed_materials.production_order_id","production_order_consumed_materials.raw_material_id","packaging_order_consumed_materials.packaging_order_id","inventory_count_items.session_id"]),from_alias:alias,alias,type:z.enum(['inner','left'])}).strict()).max(5).default([]),
 select:z.array(z.object({as:output,expr:z.union([scalarExpr,aggregate])}).strict()).min(1).max(20),
 group_by:z.array(output).max(10).default([]),
 filters:z.array(z.object({field,op:z.enum(['eq','ne','gt','gte','lt','lte','in','between','is_null','not_null']),value:z.union([scalar,z.array(scalar).min(1).max(100)]).optional()}).strict()).max(20).default([]),
 order_by:z.array(z.object({as:output,direction:z.enum(['asc','desc'])}).strict()).max(20).default([]),
 offset:z.number().int().nonnegative().max(1000000).default(0),
 limit:z.number().int().min(1).max(250).default(100)
}).strict();
export const schemaDiscovery=z.object({table:z.enum(["raw_materials","packaging_materials","semi_finished_products","finished_products","product_bundles","parties","treasuries","financial_categories","financial_transactions","sales_invoices","purchase_invoices","sales_invoice_items","purchase_invoice_items","sales_returns","purchase_returns","sales_return_items","purchase_return_items","production_orders","packaging_orders","bundle_assembly_orders","production_order_items","packaging_order_items","bundle_assembly_order_items","semi_finished_ingredients","finished_product_packaging","bundle_items","production_order_consumed_materials","packaging_order_consumed_materials","inventory_count_sessions","inventory_count_items","inventory_movements"]).optional()}).strict();
// SQL remains the authoritative cross-table, alias, field-type, domain and group validator.
export const tools={
 factory_schema:{schema:schemaDiscovery,description:'Discover allowed factory business base tables, typed columns and fixed relationships for the signed-in role. Auth, credentials and unsafe views are excluded.'},
 factory_analyze:{schema:analyticalQuery,description:'Run a structured read-only analysis against real source RLS. Aggregations cover all filtered rows before pagination. This accepts no SQL, function calls, raw expressions, arbitrary join predicates or arbitrary tables.'}
};
