-- Invoices Schema
-- 1. Purchase Invoices (Buying Raw/Packaging Materials)
CREATE TABLE IF NOT EXISTS purchase_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT, -- Manual or Auto generated
    supplier_id UUID REFERENCES parties(id) ON DELETE RESTRICT, -- Must exist
    treasury_id BIGINT REFERENCES treasuries(id) ON DELETE SET NULL, -- Voluntary: if paid immediately
    
    transaction_date DATE DEFAULT CURRENT_DATE,
    
    total_amount NUMERIC NOT NULL DEFAULT 0,
    paid_amount NUMERIC DEFAULT 0, -- Amount paid from treasury
    tax_amount NUMERIC DEFAULT 0,
    discount_amount NUMERIC DEFAULT 0,
    shipping_cost NUMERIC DEFAULT 0, -- Added for extra expenses
    
    status TEXT DEFAULT 'draft', -- draft, posted, void
    notes TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Items for Purchase Invoices (Can be Raw Material or Packaging)
CREATE TABLE IF NOT EXISTS purchase_invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT REFERENCES purchase_invoices(id) ON DELETE CASCADE,
    
    item_type TEXT NOT NULL CHECK (item_type IN ('raw_material', 'packaging_material', 'finished_product', 'semi_finished')),
    
    -- Links to Inventory (Only one should be set)
    raw_material_id BIGINT REFERENCES raw_materials(id),
    packaging_material_id BIGINT REFERENCES packaging_materials(id),
    finished_product_id BIGINT REFERENCES finished_products(id),
    semi_finished_product_id BIGINT REFERENCES semi_finished_products(id),
    
    quantity NUMERIC NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC NOT NULL DEFAULT 0,
    total_price NUMERIC NOT NULL DEFAULT 0, -- quantity * unit_price
    
    CONSTRAINT check_purchase_item_source CHECK (
        (item_type = 'raw_material' AND raw_material_id IS NOT NULL AND packaging_material_id IS NULL AND finished_product_id IS NULL AND semi_finished_product_id IS NULL) OR
        (item_type = 'packaging_material' AND packaging_material_id IS NOT NULL AND raw_material_id IS NULL AND finished_product_id IS NULL AND semi_finished_product_id IS NULL) OR
        (item_type = 'finished_product' AND finished_product_id IS NOT NULL AND raw_material_id IS NULL AND packaging_material_id IS NULL AND semi_finished_product_id IS NULL) OR
        (item_type = 'semi_finished' AND semi_finished_product_id IS NOT NULL AND raw_material_id IS NULL AND packaging_material_id IS NULL AND finished_product_id IS NULL)
    )
);

-- 2. Sales Invoices (Selling Finished Products)
CREATE TABLE IF NOT EXISTS sales_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT,
    customer_id UUID REFERENCES parties(id) ON DELETE RESTRICT,
    treasury_id BIGINT REFERENCES treasuries(id) ON DELETE SET NULL,
    
    transaction_date DATE DEFAULT CURRENT_DATE,
    
    total_amount NUMERIC NOT NULL DEFAULT 0,
    paid_amount NUMERIC DEFAULT 0,
    tax_amount NUMERIC DEFAULT 0,
    discount_amount NUMERIC DEFAULT 0,
    shipping_cost NUMERIC DEFAULT 0,
    
    status TEXT DEFAULT 'draft',
    notes TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sales_invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT REFERENCES sales_invoices(id) ON DELETE CASCADE,
    
    item_type TEXT NOT NULL CHECK (item_type IN ('raw_material', 'packaging_material', 'finished_product', 'semi_finished')),

    finished_product_id BIGINT REFERENCES finished_products(id),
    raw_material_id BIGINT REFERENCES raw_materials(id),
    packaging_material_id BIGINT REFERENCES packaging_materials(id),
    semi_finished_product_id BIGINT REFERENCES semi_finished_products(id),
    
    quantity NUMERIC NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC NOT NULL DEFAULT 0,
    total_price NUMERIC NOT NULL DEFAULT 0,

    CONSTRAINT check_sales_item_source CHECK (
        (item_type = 'raw_material' AND raw_material_id IS NOT NULL AND packaging_material_id IS NULL AND finished_product_id IS NULL AND semi_finished_product_id IS NULL) OR
        (item_type = 'packaging_material' AND packaging_material_id IS NOT NULL AND raw_material_id IS NULL AND finished_product_id IS NULL AND semi_finished_product_id IS NULL) OR
        (item_type = 'finished_product' AND finished_product_id IS NOT NULL AND raw_material_id IS NULL AND packaging_material_id IS NULL AND semi_finished_product_id IS NULL) OR
        (item_type = 'semi_finished' AND semi_finished_product_id IS NOT NULL AND raw_material_id IS NULL AND packaging_material_id IS NULL AND finished_product_id IS NULL)
    )
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_purchase_invoices_supplier ON purchase_invoices(supplier_id);
CREATE INDEX IF NOT EXISTS idx_sales_invoices_customer ON sales_invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_purchase_items_invoice ON purchase_invoice_items(invoice_id);
CREATE INDEX IF NOT EXISTS idx_sales_items_invoice ON sales_invoice_items(invoice_id);
