-- Ensure production_orders table exists
CREATE TABLE IF NOT EXISTS production_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT NOT NULL DEFAULT 'pending', -- 'pending' | 'inProgress' | 'completed' | 'cancelled'
  notes TEXT,
  total_cost NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Re-create production_order_items to match our new logic (Foreign Key to semi_finished_products)
DROP TABLE IF EXISTS production_order_items;

CREATE TABLE production_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id BIGINT REFERENCES production_orders(id) ON DELETE CASCADE,
  
  -- Link to Semi-Finished Product directly
  semi_finished_id BIGINT REFERENCES semi_finished_products(id) ON DELETE RESTRICT,
  
  quantity NUMERIC NOT NULL,
  unit_cost NUMERIC DEFAULT 0,
  total_cost NUMERIC DEFAULT 0,
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_production_order_items_order ON production_order_items(production_order_id);
