-- Ensure packaging_orders table exists
CREATE TABLE IF NOT EXISTS packaging_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT NOT NULL DEFAULT 'pending', -- 'pending' | 'inProgress' | 'completed' | 'cancelled'
  notes TEXT,
  total_cost NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Re-create packaging_order_items to match logic (Foreign Key to finished_products)
DROP TABLE IF EXISTS packaging_order_items;

CREATE TABLE packaging_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  packaging_order_id BIGINT REFERENCES packaging_orders(id) ON DELETE CASCADE,
  
  -- Link to Finished Product directly
  finished_product_id BIGINT REFERENCES finished_products(id) ON DELETE RESTRICT,
  
  quantity NUMERIC NOT NULL,
  unit_cost NUMERIC DEFAULT 0,
  total_cost NUMERIC DEFAULT 0,
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_packaging_order_items_order ON packaging_order_items(packaging_order_id);
