-- Create production_order_items table
CREATE TABLE IF NOT EXISTS production_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id BIGINT REFERENCES production_orders(id) ON DELETE CASCADE,
  product_code TEXT NOT NULL,
  product_name TEXT NOT NULL,
  quantity NUMERIC NOT NULL,
  unit TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create packaging_order_items table
CREATE TABLE IF NOT EXISTS packaging_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  packaging_order_id BIGINT REFERENCES packaging_orders(id) ON DELETE CASCADE,
  product_code TEXT NOT NULL,
  product_name TEXT NOT NULL,
  quantity NUMERIC NOT NULL,
  unit TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_production_order_items_order_id ON production_order_items(production_order_id);
CREATE INDEX IF NOT EXISTS idx_packaging_order_items_order_id ON packaging_order_items(packaging_order_id);
