-- Inventory Count Sessions
CREATE TABLE IF NOT EXISTS inventory_count_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    type TEXT NOT NULL CHECK (type IN ('full', 'partial')),
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'in_progress', 'completed', 'cancelled')),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Inventory Count Items (Snapshots)
CREATE TABLE IF NOT EXISTS inventory_count_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES inventory_count_sessions(id) ON DELETE CASCADE,
    
    item_type TEXT NOT NULL CHECK (item_type IN ('raw_material', 'packaging_material', 'semi_finished', 'finished_product')),
    item_id BIGINT NOT NULL,
    
    product_name TEXT NOT NULL, -- Snapshot of name for display safety
    unit TEXT, -- Snapshot of unit
    
    system_quantity NUMERIC NOT NULL DEFAULT 0, -- The snapshot "Expected" quantity
    counted_quantity NUMERIC DEFAULT 0, -- The "Actual" quantity entered by user
    
    difference NUMERIC GENERATED ALWAYS AS (counted_quantity - system_quantity) STORED,
    
    unit_cost NUMERIC DEFAULT 0,
    cost_impact NUMERIC DEFAULT 0, -- Calculated manually or via trigger
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_inventory_count_items_session ON inventory_count_items(session_id);
CREATE INDEX IF NOT EXISTS idx_inventory_count_items_type_id ON inventory_count_items(item_type, item_id);

-- Computed Column for Cost Impact? Or simple View?
-- Let's keep cost_impact simple update for now or handle in RPC.
