-- Commercial & Financial Module Schema
-- Fixed: Use UUID for Parties to match full_schema.sql

-- 1. Treasuries (Safes & Bank Accounts)
CREATE TABLE IF NOT EXISTS treasuries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('cash', 'bank')),
    balance NUMERIC NOT NULL DEFAULT 0,
    currency TEXT DEFAULT 'EGP',
    account_number TEXT, -- For banks
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Parties (Suppliers & Customers)
-- Note: existing schema might use UUID. We ensure compatibility.
CREATE TABLE IF NOT EXISTS parties (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('supplier', 'customer')),
    phone TEXT,
    email TEXT,
    address TEXT,
    balance NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add new columns if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'parties' AND column_name = 'tax_number') THEN
        ALTER TABLE parties ADD COLUMN tax_number TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'parties' AND column_name = 'commercial_record') THEN
        ALTER TABLE parties ADD COLUMN commercial_record TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'parties' AND column_name = 'credit_limit') THEN
        ALTER TABLE parties ADD COLUMN credit_limit NUMERIC DEFAULT 0;
    END IF;
END $$;

-- 3. Financial Transactions (Ledger)
CREATE TABLE IF NOT EXISTS financial_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treasury_id BIGINT REFERENCES treasuries(id) ON DELETE RESTRICT,
    party_id UUID REFERENCES parties(id) ON DELETE SET NULL, -- CHANGED TO UUID
    
    amount NUMERIC NOT NULL,
    transaction_type TEXT NOT NULL CHECK (transaction_type IN ('income', 'expense', 'transfer')),
    
    category TEXT NOT NULL,
    description TEXT,
    
    reference_type TEXT,
    reference_id TEXT, -- Changed to TEXT to be flexible (UUID or Int ID)
    
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_financial_transactions_treasury ON financial_transactions(treasury_id);
CREATE INDEX IF NOT EXISTS idx_financial_transactions_party ON financial_transactions(party_id);
CREATE INDEX IF NOT EXISTS idx_financial_transactions_date ON financial_transactions(transaction_date);
