-- Create Financial Categories Table
CREATE TABLE IF NOT EXISTS financial_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
    is_system BOOLEAN DEFAULT FALSE, -- If true, cannot be deleted (optional logic in app)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    UNIQUE(name, type)
);

-- RLS
ALTER TABLE financial_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all authenticated users" ON financial_categories
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Enable all access for authenticated users" ON financial_categories
    FOR ALL USING (auth.role() = 'authenticated');

-- Seed Default Categories
INSERT INTO financial_categories (name, type, is_system) VALUES
('rent', 'expense', true),
('salaries', 'expense', true),
('utilities', 'expense', true),
('maintenance', 'expense', true),
('marketing', 'expense', true),
('transport', 'expense', true),
('general', 'expense', true)
ON CONFLICT (name, type) DO NOTHING;
