-- ============================================================================
-- Migration: Product Bundles System (Multi-Type Support)
-- Date: 2026-01-30
-- Purpose: Complete bundle management system with all item types support
-- RISK LEVEL: 🟢 ZERO - New tables and functions only
-- IDEMPOTENT: Safe to run multiple times
-- ============================================================================

-- ============================================================================
-- PART 1: CORE TABLES
-- ============================================================================

-- 1. Product Bundles (حزم المنتجات)
CREATE TABLE IF NOT EXISTS product_bundles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    quantity NUMERIC NOT NULL DEFAULT 0,
    min_stock NUMERIC DEFAULT 0,
    unit_cost NUMERIC NOT NULL DEFAULT 0,
    bundle_price NUMERIC NOT NULL DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Bundle Items (مكونات الحزمة - كافة الأنواع)
CREATE TABLE IF NOT EXISTS bundle_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bundle_id BIGINT NOT NULL REFERENCES product_bundles(id) ON DELETE CASCADE,
    
    -- نوع المكون
    item_type TEXT NOT NULL CHECK (item_type IN (
        'finished_product', 
        'semi_finished', 
        'raw_material', 
        'packaging_material'
    )),
    
    -- المراجع (واحد فقط سيكون له قيمة حسب النوع)
    finished_product_id BIGINT REFERENCES finished_products(id) ON DELETE RESTRICT,
    semi_finished_product_id BIGINT REFERENCES semi_finished_products(id) ON DELETE RESTRICT,
    raw_material_id BIGINT REFERENCES raw_materials(id) ON DELETE RESTRICT,
    packaging_material_id BIGINT REFERENCES packaging_materials(id) ON DELETE RESTRICT,
    
    quantity NUMERIC NOT NULL CHECK (quantity > 0),
    unit_cost NUMERIC DEFAULT 0,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- التحقق من أن المرجع المناسب موجود حسب النوع
    CONSTRAINT valid_item_reference CHECK (
        (item_type = 'finished_product' AND finished_product_id IS NOT NULL 
            AND semi_finished_product_id IS NULL AND raw_material_id IS NULL AND packaging_material_id IS NULL) OR
        (item_type = 'semi_finished' AND semi_finished_product_id IS NOT NULL 
            AND finished_product_id IS NULL AND raw_material_id IS NULL AND packaging_material_id IS NULL) OR
        (item_type = 'raw_material' AND raw_material_id IS NOT NULL 
            AND finished_product_id IS NULL AND semi_finished_product_id IS NULL AND packaging_material_id IS NULL) OR
        (item_type = 'packaging_material' AND packaging_material_id IS NOT NULL 
            AND finished_product_id IS NULL AND semi_finished_product_id IS NULL AND raw_material_id IS NULL)
    )
);

-- ============================================================================
-- PART 2: ASSEMBLY ORDERS
-- ============================================================================

-- 3. Bundle Assembly Orders (أوامر تجميع الباندلز)
CREATE TABLE IF NOT EXISTS bundle_assembly_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    status TEXT NOT NULL DEFAULT 'pending' 
        CHECK (status IN ('pending', 'inProgress', 'completed', 'cancelled')),
    notes TEXT,
    total_cost NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Bundle Assembly Order Items
CREATE TABLE IF NOT EXISTS bundle_assembly_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assembly_order_id BIGINT NOT NULL REFERENCES bundle_assembly_orders(id) ON DELETE CASCADE,
    bundle_id BIGINT NOT NULL REFERENCES product_bundles(id) ON DELETE RESTRICT,
    quantity NUMERIC NOT NULL CHECK (quantity > 0),
    unit_cost NUMERIC DEFAULT 0,
    total_cost NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- PART 3: INDEXES (IF NOT EXISTS pattern)
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_bundle_items_bundle ON bundle_items(bundle_id);
CREATE INDEX IF NOT EXISTS idx_bundle_items_type ON bundle_items(item_type);
CREATE INDEX IF NOT EXISTS idx_bundles_active ON product_bundles(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_bundles_code ON product_bundles(code);
CREATE INDEX IF NOT EXISTS idx_assembly_orders_status ON bundle_assembly_orders(status);
CREATE INDEX IF NOT EXISTS idx_assembly_order_items_order ON bundle_assembly_order_items(assembly_order_id);

-- ============================================================================
-- PART 4: RPC FUNCTIONS (CREATE OR REPLACE for idempotency)
-- ============================================================================

-- 4.1 حساب تكلفة الباندل (كافة الأنواع)
CREATE OR REPLACE FUNCTION calculate_bundle_cost(p_bundle_id BIGINT)
RETURNS NUMERIC
LANGUAGE plpgsql
AS $$
DECLARE
    v_item RECORD;
    v_total NUMERIC := 0;
    v_item_cost NUMERIC;
BEGIN
    FOR v_item IN SELECT * FROM bundle_items WHERE bundle_id = p_bundle_id LOOP
        v_item_cost := 0;
        
        IF v_item.item_type = 'finished_product' THEN
            SELECT COALESCE(unit_cost, 0) INTO v_item_cost 
            FROM finished_products WHERE id = v_item.finished_product_id;
        ELSIF v_item.item_type = 'semi_finished' THEN
            SELECT COALESCE(unit_cost, 0) INTO v_item_cost 
            FROM semi_finished_products WHERE id = v_item.semi_finished_product_id;
        ELSIF v_item.item_type = 'raw_material' THEN
            SELECT COALESCE(unit_cost, 0) INTO v_item_cost 
            FROM raw_materials WHERE id = v_item.raw_material_id;
        ELSIF v_item.item_type = 'packaging_material' THEN
            SELECT COALESCE(unit_cost, 0) INTO v_item_cost 
            FROM packaging_materials WHERE id = v_item.packaging_material_id;
        END IF;
        
        -- تحديث تكلفة المكون
        UPDATE bundle_items SET unit_cost = v_item_cost WHERE id = v_item.id;
        
        v_total := v_total + (v_item.quantity * v_item_cost);
    END LOOP;
    
    UPDATE product_bundles SET unit_cost = v_total WHERE id = p_bundle_id;
    RETURN v_total;
END;
$$;

-- 4.2 التحقق من توفر المخزون للتجميع (كافة الأنواع)
CREATE OR REPLACE FUNCTION check_bundle_assembly_availability(p_bundle_id BIGINT, p_quantity NUMERIC)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_item RECORD;
    v_needed NUMERIC;
    v_available NUMERIC;
    v_name TEXT;
    v_shortages JSONB := '[]'::jsonb;
BEGIN
    FOR v_item IN SELECT * FROM bundle_items WHERE bundle_id = p_bundle_id LOOP
        v_needed := v_item.quantity * p_quantity;
        v_available := 0;
        v_name := '';
        
        IF v_item.item_type = 'finished_product' THEN
            SELECT name, quantity INTO v_name, v_available 
            FROM finished_products WHERE id = v_item.finished_product_id;
        ELSIF v_item.item_type = 'semi_finished' THEN
            SELECT name, quantity INTO v_name, v_available 
            FROM semi_finished_products WHERE id = v_item.semi_finished_product_id;
        ELSIF v_item.item_type = 'raw_material' THEN
            SELECT name, quantity INTO v_name, v_available 
            FROM raw_materials WHERE id = v_item.raw_material_id;
        ELSIF v_item.item_type = 'packaging_material' THEN
            SELECT name, quantity INTO v_name, v_available 
            FROM packaging_materials WHERE id = v_item.packaging_material_id;
        END IF;
        
        IF COALESCE(v_available, 0) < v_needed THEN
            v_shortages := v_shortages || jsonb_build_object(
                'item_type', v_item.item_type,
                'name', v_name,
                'required', v_needed,
                'available', COALESCE(v_available, 0),
                'shortage', v_needed - COALESCE(v_available, 0)
            );
        END IF;
    END LOOP;
    
    RETURN jsonb_build_object(
        'available', jsonb_array_length(v_shortages) = 0,
        'shortages', v_shortages
    );
END;
$$;

-- 4.3 تنفيذ أمر التجميع الذري (كافة الأنواع)
CREATE OR REPLACE FUNCTION complete_bundle_assembly_order_atomic(p_order_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    r_order_item RECORD;
    r_bundle_item RECORD;
    v_order_code TEXT;
    v_qty_needed NUMERIC;
    v_prev_balance NUMERIC;
    v_new_balance NUMERIC;
    v_item_name TEXT;
    v_bundle_cost NUMERIC;
    v_prev_bundle_qty NUMERIC;
    v_prev_bundle_cost NUMERIC;
    v_new_bundle_cost NUMERIC;
    v_total_order_cost NUMERIC := 0;
    v_table_name TEXT;
    v_item_id BIGINT;
BEGIN
    -- الحصول على كود الأمر
    SELECT code INTO v_order_code FROM bundle_assembly_orders WHERE id = p_order_id;
    IF v_order_code IS NULL THEN 
        v_order_code := 'BA-' || p_order_id::TEXT; 
    END IF;

    -- التحقق من حالة الأمر
    IF NOT EXISTS (SELECT 1 FROM bundle_assembly_orders WHERE id = p_order_id AND status = 'pending') THEN
        RAISE EXCEPTION 'أمر التجميع غير موجود أو تم تنفيذه مسبقاً';
    END IF;

    -- تحديث الحالة إلى قيد التنفيذ
    UPDATE bundle_assembly_orders SET status = 'inProgress', updated_at = NOW() WHERE id = p_order_id;

    -- المرور على كل عنصر في الأمر
    FOR r_order_item IN 
        SELECT * FROM bundle_assembly_order_items WHERE assembly_order_id = p_order_id 
    LOOP
        -- حساب تكلفة الباندل
        v_bundle_cost := calculate_bundle_cost(r_order_item.bundle_id);
        
        -- خصم المكونات من المخزون
        FOR r_bundle_item IN 
            SELECT * FROM bundle_items WHERE bundle_id = r_order_item.bundle_id
        LOOP
            v_qty_needed := r_bundle_item.quantity * r_order_item.quantity;
            v_prev_balance := 0;
            v_item_name := '';
            v_item_id := NULL;
            v_table_name := '';
            
            -- تحديد الجدول والـ ID بناء على النوع
            IF r_bundle_item.item_type = 'finished_product' THEN
                v_table_name := 'finished_products';
                v_item_id := r_bundle_item.finished_product_id;
                SELECT name, quantity INTO v_item_name, v_prev_balance 
                FROM finished_products WHERE id = v_item_id;
                
            ELSIF r_bundle_item.item_type = 'semi_finished' THEN
                v_table_name := 'semi_finished_products';
                v_item_id := r_bundle_item.semi_finished_product_id;
                SELECT name, quantity INTO v_item_name, v_prev_balance 
                FROM semi_finished_products WHERE id = v_item_id;
                
            ELSIF r_bundle_item.item_type = 'raw_material' THEN
                v_table_name := 'raw_materials';
                v_item_id := r_bundle_item.raw_material_id;
                SELECT name, quantity INTO v_item_name, v_prev_balance 
                FROM raw_materials WHERE id = v_item_id;
                
            ELSIF r_bundle_item.item_type = 'packaging_material' THEN
                v_table_name := 'packaging_materials';
                v_item_id := r_bundle_item.packaging_material_id;
                SELECT name, quantity INTO v_item_name, v_prev_balance 
                FROM packaging_materials WHERE id = v_item_id;
            END IF;
            
            -- التحقق من الرصيد
            IF COALESCE(v_prev_balance, 0) < v_qty_needed THEN
                -- إعادة الحالة إلى pending في حالة الفشل
                UPDATE bundle_assembly_orders SET status = 'pending', updated_at = NOW() WHERE id = p_order_id;
                RAISE EXCEPTION 'رصيد غير كافٍ لـ %: المطلوب % والمتاح %', 
                    v_item_name, v_qty_needed, COALESCE(v_prev_balance, 0);
            END IF;
            
            v_new_balance := v_prev_balance - v_qty_needed;
            
            -- خصم المخزون بناء على النوع
            IF r_bundle_item.item_type = 'finished_product' THEN
                UPDATE finished_products SET quantity = v_new_balance, updated_at = NOW()
                WHERE id = v_item_id;
            ELSIF r_bundle_item.item_type = 'semi_finished' THEN
                UPDATE semi_finished_products SET quantity = v_new_balance, updated_at = NOW()
                WHERE id = v_item_id;
            ELSIF r_bundle_item.item_type = 'raw_material' THEN
                UPDATE raw_materials SET quantity = v_new_balance, updated_at = NOW()
                WHERE id = v_item_id;
            ELSIF r_bundle_item.item_type = 'packaging_material' THEN
                UPDATE packaging_materials SET quantity = v_new_balance, updated_at = NOW()
                WHERE id = v_item_id;
            END IF;
            
            -- تسجيل حركة المخزون
            PERFORM log_inventory_movement(
                v_item_id,
                v_table_name,
                'out',
                v_qty_needed,
                'تجميع باندل - أمر #' || v_order_code,
                'BA-' || p_order_id::TEXT
            );
        END LOOP;
        
        -- إضافة الكمية للباندل مع حساب WACO
        SELECT quantity, COALESCE(unit_cost, 0) 
        INTO v_prev_bundle_qty, v_prev_bundle_cost
        FROM product_bundles WHERE id = r_order_item.bundle_id;
        
        v_prev_bundle_qty := COALESCE(v_prev_bundle_qty, 0);
        v_new_balance := v_prev_bundle_qty + r_order_item.quantity;
        
        -- حساب متوسط التكلفة المرجح
        IF v_new_balance > 0 THEN
            v_new_bundle_cost := ((v_prev_bundle_qty * v_prev_bundle_cost) + 
                                  (r_order_item.quantity * v_bundle_cost)) / v_new_balance;
        ELSE
            v_new_bundle_cost := v_bundle_cost;
        END IF;
        
        -- تحديث مخزون وتكلفة الباندل
        UPDATE product_bundles 
        SET quantity = v_new_balance,
            unit_cost = v_new_bundle_cost,
            updated_at = NOW()
        WHERE id = r_order_item.bundle_id;
        
        -- تحديث تكلفة عنصر الأمر
        UPDATE bundle_assembly_order_items
        SET unit_cost = v_bundle_cost,
            total_cost = r_order_item.quantity * v_bundle_cost
        WHERE id = r_order_item.id;
        
        v_total_order_cost := v_total_order_cost + (r_order_item.quantity * v_bundle_cost);
    END LOOP;

    -- تحديث الأمر كمكتمل
    UPDATE bundle_assembly_orders 
    SET status = 'completed',
        total_cost = v_total_order_cost,
        updated_at = NOW()
    WHERE id = p_order_id;
END;
$$;

-- 4.4 إلغاء أمر تجميع (للأوامر غير المنفذة)
CREATE OR REPLACE FUNCTION cancel_bundle_assembly_order(p_order_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_status TEXT;
BEGIN
    SELECT status INTO v_status FROM bundle_assembly_orders WHERE id = p_order_id;
    
    IF v_status IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'الأمر غير موجود');
    END IF;
    
    IF v_status = 'completed' THEN
        RETURN jsonb_build_object('success', false, 'message', 'لا يمكن إلغاء أمر تم تنفيذه');
    END IF;
    
    IF v_status = 'cancelled' THEN
        RETURN jsonb_build_object('success', false, 'message', 'الأمر ملغي بالفعل');
    END IF;
    
    UPDATE bundle_assembly_orders 
    SET status = 'cancelled', updated_at = NOW() 
    WHERE id = p_order_id;
    
    RETURN jsonb_build_object('success', true, 'message', 'تم إلغاء الأمر بنجاح');
END;
$$;

-- ============================================================================
-- PART 5: SALES INVOICE SUPPORT (Optional column)
-- ============================================================================

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'sales_invoice_items' AND column_name = 'bundle_id'
    ) THEN
        ALTER TABLE sales_invoice_items 
        ADD COLUMN bundle_id BIGINT REFERENCES product_bundles(id);
    END IF;
END
$$;

-- ============================================================================
-- PART 6: RLS POLICIES (DROP IF EXISTS + CREATE pattern)
-- ============================================================================

ALTER TABLE product_bundles ENABLE ROW LEVEL SECURITY;
ALTER TABLE bundle_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE bundle_assembly_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE bundle_assembly_order_items ENABLE ROW LEVEL SECURITY;

-- Product Bundles
DROP POLICY IF EXISTS "Auth users manage bundles" ON product_bundles;
CREATE POLICY "Auth users manage bundles" ON product_bundles
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Bundle Items
DROP POLICY IF EXISTS "Auth users manage bundle items" ON bundle_items;
CREATE POLICY "Auth users manage bundle items" ON bundle_items
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Assembly Orders
DROP POLICY IF EXISTS "Auth users manage assembly orders" ON bundle_assembly_orders;
CREATE POLICY "Auth users manage assembly orders" ON bundle_assembly_orders
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Assembly Order Items
DROP POLICY IF EXISTS "Auth users manage assembly items" ON bundle_assembly_order_items;
CREATE POLICY "Auth users manage assembly items" ON bundle_assembly_order_items
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============================================================================
-- PART 7: COMMENTS & DOCUMENTATION
-- ============================================================================

COMMENT ON TABLE product_bundles IS 'حزم المنتجات - تجميع عدة منتجات في حزمة واحدة للبيع';
COMMENT ON TABLE bundle_items IS 'مكونات الحزمة - تدعم كل أنواع المنتجات (نهائي، نصف مصنع، خام، تعبئة)';
COMMENT ON TABLE bundle_assembly_orders IS 'أوامر تجميع الحزم';
COMMENT ON TABLE bundle_assembly_order_items IS 'عناصر أوامر التجميع';

COMMENT ON FUNCTION calculate_bundle_cost(BIGINT) IS 'حساب تكلفة الحزمة من تكاليف مكوناتها';
COMMENT ON FUNCTION check_bundle_assembly_availability(BIGINT, NUMERIC) IS 'التحقق من توفر المخزون للتجميع';
COMMENT ON FUNCTION complete_bundle_assembly_order_atomic(BIGINT) IS 'تنفيذ أمر تجميع حزمة بشكل ذري - يخصم المكونات ويضيف للحزمة';
COMMENT ON FUNCTION cancel_bundle_assembly_order(BIGINT) IS 'إلغاء أمر تجميع غير منفذ';

-- ============================================================================
-- PART 8: AUTO-CODE GENERATION SEQUENCE
-- ============================================================================

-- Sequence for bundle codes
CREATE SEQUENCE IF NOT EXISTS bundle_code_seq START WITH 1;
CREATE SEQUENCE IF NOT EXISTS bundle_assembly_code_seq START WITH 1;

-- Function to generate next bundle code
CREATE OR REPLACE FUNCTION generate_bundle_code()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    v_next INT;
BEGIN
    SELECT COALESCE(MAX(NULLIF(regexp_replace(code, '[^0-9]', '', 'g'), '')::INT), 0) + 1
    INTO v_next
    FROM product_bundles;
    
    RETURN 'BND-' || LPAD(v_next::TEXT, 3, '0');
END;
$$;

-- Function to generate next assembly order code
CREATE OR REPLACE FUNCTION generate_bundle_assembly_code()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    v_next INT;
BEGIN
    SELECT COALESCE(MAX(NULLIF(regexp_replace(code, '[^0-9]', '', 'g'), '')::INT), 0) + 1
    INTO v_next
    FROM bundle_assembly_orders;
    
    RETURN 'BA-' || LPAD(v_next::TEXT, 3, '0');
END;
$$;

-- ============================================================================
-- PART 9: BUNDLE SALES INTEGRATION
-- تكامل بيع الباندلات مع نظام الفواتير والمرتجعات
-- ============================================================================

-- 9.1 إضافة قيمة product_bundles إلى item_type_enum
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_enum 
        WHERE enumlabel = 'product_bundles' 
        AND enumtypid = 'item_type_enum'::regtype
    ) THEN
        ALTER TYPE item_type_enum ADD VALUE IF NOT EXISTS 'product_bundles';
    END IF;
EXCEPTION WHEN others THEN
    -- Enum value might already exist, ignore
    NULL;
END
$$;

-- 9.2 تعديل CHECK Constraint لـ item_type في sales_invoice_items
ALTER TABLE sales_invoice_items 
DROP CONSTRAINT IF EXISTS sales_invoice_items_item_type_check;

ALTER TABLE sales_invoice_items 
ADD CONSTRAINT sales_invoice_items_item_type_check 
CHECK (item_type IN ('raw_material', 'packaging_material', 'finished_product', 'semi_finished', 'bundle'));

-- 9.3 تعديل CONSTRAINT check_sales_item_source
ALTER TABLE sales_invoice_items 
DROP CONSTRAINT IF EXISTS check_sales_item_source;

ALTER TABLE sales_invoice_items 
ADD CONSTRAINT check_sales_item_source CHECK (
    (item_type = 'raw_material' AND raw_material_id IS NOT NULL AND packaging_material_id IS NULL AND finished_product_id IS NULL AND semi_finished_product_id IS NULL AND bundle_id IS NULL) OR
    (item_type = 'packaging_material' AND packaging_material_id IS NOT NULL AND raw_material_id IS NULL AND finished_product_id IS NULL AND semi_finished_product_id IS NULL AND bundle_id IS NULL) OR
    (item_type = 'finished_product' AND finished_product_id IS NOT NULL AND raw_material_id IS NULL AND packaging_material_id IS NULL AND semi_finished_product_id IS NULL AND bundle_id IS NULL) OR
    (item_type = 'semi_finished' AND semi_finished_product_id IS NOT NULL AND raw_material_id IS NULL AND packaging_material_id IS NULL AND finished_product_id IS NULL AND bundle_id IS NULL) OR
    (item_type = 'bundle' AND bundle_id IS NOT NULL AND raw_material_id IS NULL AND packaging_material_id IS NULL AND finished_product_id IS NULL AND semi_finished_product_id IS NULL)
);

-- 9.4 إضافة bundle_id إلى sales_return_items
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'sales_return_items' AND column_name = 'bundle_id'
    ) THEN
        ALTER TABLE sales_return_items 
        ADD COLUMN bundle_id BIGINT REFERENCES product_bundles(id);
    END IF;
END
$$;

-- ============================================================================
-- PART 10: ENHANCED log_inventory_movement (مع دعم الباندل)
-- ============================================================================

CREATE OR REPLACE FUNCTION log_inventory_movement(
    p_item_id BIGINT,
    p_item_type TEXT,
    p_movement_type TEXT,
    p_quantity NUMERIC,
    p_reason TEXT,
    p_reference_id TEXT
) RETURNS VOID AS $$
DECLARE
    v_prev_balance NUMERIC;
    v_new_balance NUMERIC;
    v_table_name TEXT;
BEGIN
    IF p_item_type = 'raw_materials' OR p_item_type = 'raw_material' THEN
        SELECT quantity INTO v_new_balance FROM raw_materials WHERE id = p_item_id;
        v_table_name := 'raw_materials';
    ELSIF p_item_type = 'packaging_materials' OR p_item_type = 'packaging_material' THEN
        SELECT quantity INTO v_new_balance FROM packaging_materials WHERE id = p_item_id;
        v_table_name := 'packaging_materials';
    ELSIF p_item_type = 'semi_finished_products' OR p_item_type = 'semi_finished' THEN
        SELECT quantity INTO v_new_balance FROM semi_finished_products WHERE id = p_item_id;
        v_table_name := 'semi_finished_products';
    ELSIF p_item_type = 'finished_products' OR p_item_type = 'finished_product' THEN
        SELECT quantity INTO v_new_balance FROM finished_products WHERE id = p_item_id;
        v_table_name := 'finished_products';
    -- ===== NEW: Bundle Support =====
    ELSIF p_item_type = 'product_bundles' OR p_item_type = 'bundle' THEN
        SELECT quantity INTO v_new_balance FROM product_bundles WHERE id = p_item_id;
        v_table_name := 'product_bundles';
    -- ===============================
    ELSE
        RETURN;
    END IF;

    IF p_movement_type = 'in' THEN
        v_prev_balance := v_new_balance - p_quantity;
    ELSE
        v_prev_balance := v_new_balance + p_quantity;
    END IF;

    INSERT INTO inventory_movements (
        item_id, item_type, movement_type, quantity,
        previous_balance, new_balance, reason, reference_id
    ) VALUES (
        p_item_id, v_table_name::item_type_enum, p_movement_type, p_quantity,
        v_prev_balance, v_new_balance, p_reason, p_reference_id
    );
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- PART 11: ENHANCED process_sales_invoice (مع دعم الباندل)
-- ============================================================================

DROP FUNCTION IF EXISTS process_sales_invoice(BIGINT);

CREATE OR REPLACE FUNCTION process_sales_invoice(p_invoice_id BIGINT) RETURNS JSONB AS $$
DECLARE
    v_invoice RECORD;
    v_item RECORD;
    v_current_qty NUMERIC;
    v_current_cost NUMERIC;
    v_remaining_amount NUMERIC;
    v_item_id BIGINT;
    v_item_type_str TEXT;
BEGIN
    SELECT * INTO v_invoice FROM sales_invoices WHERE id = p_invoice_id;
    
    IF v_invoice.status != 'draft' THEN
        RAISE EXCEPTION 'Invoice is already processed or voided';
    END IF;

    FOR v_item IN SELECT * FROM sales_invoice_items WHERE invoice_id = p_invoice_id LOOP
        v_item_id := NULL;
        v_current_cost := 0;
        
        IF v_item.item_type = 'finished_product' THEN
            v_item_id := v_item.finished_product_id;
            v_item_type_str := 'finished_products';
            SELECT quantity, COALESCE(unit_cost, 0) INTO v_current_qty, v_current_cost 
            FROM finished_products WHERE id = v_item_id;
            IF v_current_qty < v_item.quantity THEN RAISE EXCEPTION 'رصيد غير كافي للمنتج #%', v_item_id; END IF;
            UPDATE finished_products SET quantity = quantity - v_item.quantity, updated_at = NOW() WHERE id = v_item_id;

        ELSIF v_item.item_type = 'raw_material' THEN
            v_item_id := v_item.raw_material_id;
            v_item_type_str := 'raw_materials';
            SELECT quantity, COALESCE(unit_cost, 0) INTO v_current_qty, v_current_cost 
            FROM raw_materials WHERE id = v_item_id;
            IF v_current_qty < v_item.quantity THEN RAISE EXCEPTION 'رصيد غير كافي للخامة #%', v_item_id; END IF;
            UPDATE raw_materials SET quantity = quantity - v_item.quantity, updated_at = NOW() WHERE id = v_item_id;

        ELSIF v_item.item_type = 'packaging_material' THEN
            v_item_id := v_item.packaging_material_id;
            v_item_type_str := 'packaging_materials';
            SELECT quantity, COALESCE(unit_cost, 0) INTO v_current_qty, v_current_cost 
            FROM packaging_materials WHERE id = v_item_id;
            IF v_current_qty < v_item.quantity THEN RAISE EXCEPTION 'رصيد غير كافي لمادة التعبئة #%', v_item_id; END IF;
            UPDATE packaging_materials SET quantity = quantity - v_item.quantity, updated_at = NOW() WHERE id = v_item_id;

        ELSIF v_item.item_type = 'semi_finished' THEN
            v_item_id := v_item.semi_finished_product_id;
            v_item_type_str := 'semi_finished_products';
            SELECT quantity, COALESCE(unit_cost, 0) INTO v_current_qty, v_current_cost 
            FROM semi_finished_products WHERE id = v_item_id;
            IF v_current_qty < v_item.quantity THEN RAISE EXCEPTION 'رصيد غير كافي للمنتج نصف المصنع #%', v_item_id; END IF;
            UPDATE semi_finished_products SET quantity = quantity - v_item.quantity, updated_at = NOW() WHERE id = v_item_id;

        -- ===== NEW: Bundle Support =====
        ELSIF v_item.item_type = 'bundle' THEN
            v_item_id := v_item.bundle_id;
            v_item_type_str := 'product_bundles';
            SELECT quantity, COALESCE(unit_cost, 0) INTO v_current_qty, v_current_cost 
            FROM product_bundles WHERE id = v_item_id;
            IF v_current_qty < v_item.quantity THEN RAISE EXCEPTION 'رصيد غير كافي للباندل #%', v_item_id; END IF;
            UPDATE product_bundles SET quantity = quantity - v_item.quantity, updated_at = NOW() WHERE id = v_item_id;
        -- ===============================
        END IF;

        UPDATE sales_invoice_items SET unit_cost_at_sale = v_current_cost WHERE id = v_item.id;

        IF v_item_id IS NOT NULL THEN
            PERFORM log_inventory_movement(
                v_item_id, v_item_type_str, 'out', v_item.quantity,
                'فاتورة بيع #' || v_invoice.invoice_number, 'SI-' || p_invoice_id::TEXT
            );
        END IF;
    END LOOP;

    IF v_invoice.paid_amount > 0 AND v_invoice.treasury_id IS NOT NULL THEN
        UPDATE treasuries SET balance = balance + v_invoice.paid_amount WHERE id = v_invoice.treasury_id;
        INSERT INTO financial_transactions (treasury_id, party_id, amount, transaction_type, category, description, reference_type, reference_id, transaction_date)
        VALUES (v_invoice.treasury_id, v_invoice.customer_id, v_invoice.paid_amount, 'income', 'sales_payment', 'تحصيل فاتورة بيع #' || v_invoice.invoice_number, 'sales_invoice', v_invoice.id::text, v_invoice.transaction_date);
    END IF;

    v_remaining_amount := v_invoice.total_amount - v_invoice.paid_amount;
    IF v_remaining_amount > 0 THEN
        UPDATE parties SET balance = balance + v_remaining_amount WHERE id = v_invoice.customer_id;
    END IF;

    UPDATE sales_invoices SET status = 'posted' WHERE id = p_invoice_id;
    RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION process_sales_invoice(BIGINT) IS 
'Processes a draft sales invoice with bundle support: deducts inventory, logs movements, captures COGS, handles treasury/customer balance.';

-- ============================================================================
-- PART 12: ENHANCED void_sales_invoice (مع دعم الباندل)
-- ============================================================================

DROP FUNCTION IF EXISTS void_sales_invoice(BIGINT);

CREATE OR REPLACE FUNCTION void_sales_invoice(p_invoice_id BIGINT) RETURNS JSONB AS $$
DECLARE
    v_invoice RECORD;
    v_item RECORD;
    v_remaining_amount NUMERIC;
    v_item_id BIGINT;
    v_item_type_str TEXT;
BEGIN
    SELECT * INTO v_invoice FROM sales_invoices WHERE id = p_invoice_id;
    
    IF v_invoice.status != 'posted' THEN
        RAISE EXCEPTION 'Invoice is not posted';
    END IF;

    FOR v_item IN SELECT * FROM sales_invoice_items WHERE invoice_id = p_invoice_id LOOP
        v_item_id := NULL;
        
        IF v_item.item_type = 'raw_material' THEN
            v_item_id := v_item.raw_material_id;
            v_item_type_str := 'raw_materials';
            UPDATE raw_materials SET quantity = quantity + v_item.quantity WHERE id = v_item_id;
        ELSIF v_item.item_type = 'packaging_material' THEN
            v_item_id := v_item.packaging_material_id;
            v_item_type_str := 'packaging_materials';
            UPDATE packaging_materials SET quantity = quantity + v_item.quantity WHERE id = v_item_id;
        ELSIF v_item.item_type = 'finished_product' THEN
            v_item_id := v_item.finished_product_id;
            v_item_type_str := 'finished_products';
            UPDATE finished_products SET quantity = quantity + v_item.quantity WHERE id = v_item_id;
        ELSIF v_item.item_type = 'semi_finished' THEN
            v_item_id := v_item.semi_finished_product_id;
            v_item_type_str := 'semi_finished_products';
            UPDATE semi_finished_products SET quantity = quantity + v_item.quantity WHERE id = v_item_id;
        -- ===== NEW: Bundle Support =====
        ELSIF v_item.item_type = 'bundle' THEN
            v_item_id := v_item.bundle_id;
            v_item_type_str := 'product_bundles';
            UPDATE product_bundles SET quantity = quantity + v_item.quantity WHERE id = v_item_id;
        -- ===============================
        END IF;

        IF v_item_id IS NOT NULL THEN
            PERFORM log_inventory_movement(
                v_item_id, v_item_type_str, 'in', v_item.quantity,
                'إلغاء فاتورة بيع #' || v_invoice.invoice_number, 'SI-VOID-' || p_invoice_id::TEXT
            );
        END IF;
    END LOOP;

    IF v_invoice.paid_amount > 0 AND v_invoice.treasury_id IS NOT NULL THEN
        IF (SELECT balance FROM treasuries WHERE id = v_invoice.treasury_id) < v_invoice.paid_amount THEN
             RAISE EXCEPTION 'رصيد الخزينة غير كافي لاسترداد المبلغ للعميل';
        END IF;
        UPDATE treasuries SET balance = balance - v_invoice.paid_amount WHERE id = v_invoice.treasury_id;
        INSERT INTO financial_transactions (treasury_id, party_id, amount, transaction_type, category, description, reference_type, reference_id, transaction_date)
        VALUES (v_invoice.treasury_id, v_invoice.customer_id, v_invoice.paid_amount, 'expense', 'sales_void_refund', 'استرداد من إلغاء فاتورة بيع #' || v_invoice.invoice_number, 'sales_invoice', v_invoice.id::text, CURRENT_DATE);
    END IF;

    v_remaining_amount := v_invoice.total_amount - v_invoice.paid_amount;
    IF v_remaining_amount > 0 THEN
        UPDATE parties SET balance = balance - v_remaining_amount WHERE id = v_invoice.customer_id;
    END IF;

    UPDATE sales_invoices SET status = 'void' WHERE id = p_invoice_id;
    RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION void_sales_invoice(BIGINT) IS 
'Voids a posted sales invoice with bundle support: returns inventory, reverses treasury/customer balance.';

-- ============================================================================
-- PART 13: ENHANCED process_sales_return (مع دعم الباندل)
-- ============================================================================

DROP FUNCTION IF EXISTS process_sales_return(BIGINT);

CREATE OR REPLACE FUNCTION process_sales_return(p_return_id BIGINT) 
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    v_return RECORD;
    v_item RECORD;
    v_item_id BIGINT;
    v_item_type_str TEXT;
    v_current_cost NUMERIC;
BEGIN
    SELECT * INTO v_return FROM sales_returns WHERE id = p_return_id;
    
    IF v_return.status = 'posted' THEN 
        RAISE EXCEPTION 'المرتجع معالج بالفعل'; 
    END IF;

    FOR v_item IN SELECT * FROM sales_return_items WHERE return_id = p_return_id LOOP
        v_item_id := NULL;
        v_current_cost := 0;
        
        IF v_item.item_type = 'raw_material' THEN
            v_item_id := v_item.raw_material_id;
            v_item_type_str := 'raw_materials';
            SELECT COALESCE(unit_cost, 0) INTO v_current_cost FROM raw_materials WHERE id = v_item_id;
            UPDATE raw_materials SET quantity = quantity + v_item.quantity, updated_at = NOW() WHERE id = v_item_id;
            
        ELSIF v_item.item_type = 'packaging_material' THEN
            v_item_id := v_item.packaging_material_id;
            v_item_type_str := 'packaging_materials';
            SELECT COALESCE(unit_cost, 0) INTO v_current_cost FROM packaging_materials WHERE id = v_item_id;
            UPDATE packaging_materials SET quantity = quantity + v_item.quantity, updated_at = NOW() WHERE id = v_item_id;
            
        ELSIF v_item.item_type = 'finished_product' THEN
            v_item_id := v_item.finished_product_id;
            v_item_type_str := 'finished_products';
            SELECT COALESCE(unit_cost, 0) INTO v_current_cost FROM finished_products WHERE id = v_item_id;
            UPDATE finished_products SET quantity = quantity + v_item.quantity, updated_at = NOW() WHERE id = v_item_id;
            
        ELSIF v_item.item_type = 'semi_finished' THEN
            v_item_id := v_item.semi_finished_product_id;
            v_item_type_str := 'semi_finished_products';
            SELECT COALESCE(unit_cost, 0) INTO v_current_cost FROM semi_finished_products WHERE id = v_item_id;
            UPDATE semi_finished_products SET quantity = quantity + v_item.quantity, updated_at = NOW() WHERE id = v_item_id;

        -- ===== NEW: Bundle Support =====
        ELSIF v_item.item_type = 'bundle' THEN
            v_item_id := v_item.bundle_id;
            v_item_type_str := 'product_bundles';
            SELECT COALESCE(unit_cost, 0) INTO v_current_cost FROM product_bundles WHERE id = v_item_id;
            UPDATE product_bundles SET quantity = quantity + v_item.quantity, updated_at = NOW() WHERE id = v_item_id;
        -- ===============================
        END IF;

        UPDATE sales_return_items SET unit_cost_at_return = v_current_cost WHERE id = v_item.id;

        IF v_item_id IS NOT NULL THEN
            PERFORM log_inventory_movement(
                v_item_id, v_item_type_str, 'in', v_item.quantity,
                'مرتجع بيع #' || COALESCE(v_return.return_number, v_return.id::TEXT), 'SR-' || p_return_id::TEXT
            );
        END IF;
    END LOOP;

    UPDATE parties SET balance = balance - v_return.total_amount WHERE id = v_return.customer_id;
    UPDATE sales_returns SET status = 'posted', updated_at = NOW() WHERE id = p_return_id;
END;
$$;

COMMENT ON FUNCTION process_sales_return(BIGINT) IS 
'Processes a sales return with bundle support: adds items to inventory, captures unit_cost_at_return, logs movements, updates customer balance.';

-- ============================================================================
-- PART 14: ENHANCED void_sales_return (مع دعم الباندل)
-- ============================================================================

DROP FUNCTION IF EXISTS void_sales_return(BIGINT);

CREATE OR REPLACE FUNCTION void_sales_return(p_return_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_return RECORD;
    v_item RECORD;
    v_item_id BIGINT;
    v_item_type_str TEXT;
    v_current_qty NUMERIC;
    v_return_number TEXT;
BEGIN
    SELECT * INTO v_return FROM sales_returns WHERE id = p_return_id;
    
    IF v_return IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'المرتجع غير موجود');
    END IF;
    
    IF v_return.status != 'posted' THEN
        RETURN jsonb_build_object('success', false, 'message', 'لا يمكن إلغاء مرتجع غير معالج');
    END IF;
    
    v_return_number := COALESCE(v_return.return_number, 'SR-' || p_return_id::TEXT);

    -- Check Stock Before Deducting
    FOR v_item IN SELECT * FROM sales_return_items WHERE return_id = p_return_id LOOP
        v_current_qty := 0;
        
        IF v_item.item_type = 'raw_material' THEN
            SELECT quantity INTO v_current_qty FROM raw_materials WHERE id = v_item.raw_material_id;
        ELSIF v_item.item_type = 'packaging_material' THEN
            SELECT quantity INTO v_current_qty FROM packaging_materials WHERE id = v_item.packaging_material_id;
        ELSIF v_item.item_type = 'finished_product' THEN
            SELECT quantity INTO v_current_qty FROM finished_products WHERE id = v_item.finished_product_id;
        ELSIF v_item.item_type = 'semi_finished' THEN
            SELECT quantity INTO v_current_qty FROM semi_finished_products WHERE id = v_item.semi_finished_product_id;
        -- ===== NEW: Bundle Support =====
        ELSIF v_item.item_type = 'bundle' THEN
            SELECT quantity INTO v_current_qty FROM product_bundles WHERE id = v_item.bundle_id;
        -- ===============================
        END IF;
        
        IF COALESCE(v_current_qty, 0) < v_item.quantity THEN
            RETURN jsonb_build_object('success', false, 'message', 'رصيد المخزون غير كافٍ لإلغاء المرتجع');
        END IF;
    END LOOP;

    -- Reverse Inventory
    FOR v_item IN SELECT * FROM sales_return_items WHERE return_id = p_return_id LOOP
        v_item_id := NULL;
        
        IF v_item.item_type = 'raw_material' THEN
            v_item_id := v_item.raw_material_id;
            v_item_type_str := 'raw_materials';
            UPDATE raw_materials SET quantity = quantity - v_item.quantity, updated_at = NOW() WHERE id = v_item_id;
        ELSIF v_item.item_type = 'packaging_material' THEN
            v_item_id := v_item.packaging_material_id;
            v_item_type_str := 'packaging_materials';
            UPDATE packaging_materials SET quantity = quantity - v_item.quantity, updated_at = NOW() WHERE id = v_item_id;
        ELSIF v_item.item_type = 'finished_product' THEN
            v_item_id := v_item.finished_product_id;
            v_item_type_str := 'finished_products';
            UPDATE finished_products SET quantity = quantity - v_item.quantity, updated_at = NOW() WHERE id = v_item_id;
        ELSIF v_item.item_type = 'semi_finished' THEN
            v_item_id := v_item.semi_finished_product_id;
            v_item_type_str := 'semi_finished_products';
            UPDATE semi_finished_products SET quantity = quantity - v_item.quantity, updated_at = NOW() WHERE id = v_item_id;
        -- ===== NEW: Bundle Support =====
        ELSIF v_item.item_type = 'bundle' THEN
            v_item_id := v_item.bundle_id;
            v_item_type_str := 'product_bundles';
            UPDATE product_bundles SET quantity = quantity - v_item.quantity, updated_at = NOW() WHERE id = v_item_id;
        -- ===============================
        END IF;

        IF v_item_id IS NOT NULL THEN
            PERFORM log_inventory_movement(
                v_item_id, v_item_type_str, 'out', v_item.quantity,
                'إلغاء مرتجع بيع #' || v_return_number, 'SR-VOID-' || p_return_id::TEXT
            );
        END IF;
    END LOOP;

    UPDATE parties SET balance = balance + v_return.total_amount WHERE id = v_return.customer_id;
    UPDATE sales_returns SET status = 'void', updated_at = NOW() WHERE id = p_return_id;

    RETURN jsonb_build_object('success', true, 'message', 'تم إلغاء مرتجع البيع بنجاح');
END;
$$;

COMMENT ON FUNCTION void_sales_return(BIGINT) IS 
'Voids a posted sales return with bundle support: removes items from inventory (with stock check), reverses customer balance.';

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
